---
title: "Testing2"
output: html_document
---

```{r}
packages = c('rgdal', 'maptools', 'spatstat', 'tmap','raster','tidyverse','sf', 'RColorBrewer', 'classInt','leaflet','ClusterR','rgeos')
for (p in packages){
if(!require(p, character.only = T)){
install.packages(p)
}
library(p,character.only = T)
}
```

# Data Preparation
```{r}
#subzone_age_gender <- st_read(dsn = "data", layer = "SUBZONE_AGE_GENDER_2016")

subzone_age_gender <- readOGR(dsn="data",layer="SUBZONE_AGE_GENDER_2016")
subzone_dwelling_type <- st_read(dsn = "data",
layer = "SUBZONE_DWELLING_TYPE_2016")

subzone_age_gender_dwelling_type  <- left_join(subzone_dwelling_type, subzone_age_gender@data, by = c("SUBZONE_N" = "SUBZONE_N"))

# qtm(subzone_age_gender_percentage, fill = "Percentage")
```

# Data Preparation
```{r}
#start <- which(colnames(subzone_age_gender_dwelling_type) == "BET65TO69")
#end <- which(colnames(subzone_age_gender_dwelling_type) == "OVER85")

# mutate(`BET65TO69` = as.numeric(as.character(`BET65TO69`))) %>%
# mutate(`BET70TO74` = as.numeric(as.character(`BET70TO74`))) %>%
# mutate(`BET75TO79` = as.numeric(as.character(`BET75TO79`))) %>%
# mutate(`BET80TO84` = as.numeric(as.character(`BET80TO84`))) %>%
# mutate(`OVER85` = as.numeric(as.character(`OVER85`))) %>%

subzone_age_gender_dwelling_type_elder <- subzone_age_gender_dwelling_type %>%
mutate(`Elder`= `BET65TO69` + `BET70TO74` + `BET75TO79` + `BET80TO84` + `OVER85` ) %>%
mutate(`PercentageElder` = (`Elder` / `TOTAL.y`) * 100) %>%
mutate(`Percentage_HDB` = (`HDB` / `TOTAL.x`) * 100) %>%
mutate(`Elder_HDB` = floor((`Percentage_HDB` / 100) * Elder)) %>%
mutate("1&2Room_Percentage" = (`ONE_TO_TWO` / `HDB`) * 100) %>%
mutate("3Room_Percentage" = (`THREE_RM` / `HDB`) * 100) %>%
mutate("4Room_Percentage" = (`FOUR_RM` / `HDB`) * 100) %>%
mutate("5Room_Percentage" = (`FIVE_RM_EX` / `HDB`) * 100) %>%
mutate("1&2Room_Elder" = (`1&2Room_Percentage` / 100) * Elder_HDB) %>%
mutate("3Room_Elder" = (`3Room_Percentage` / 100) * Elder_HDB) %>%
mutate("4Room_Elder" = (`4Room_Percentage` / 100) * Elder_HDB) %>%
mutate("5Room_Elder" = (`5Room_Percentage` / 100) * Elder_HDB) %>%
mutate("1&2Room_Elder" = if_else(is.na(`1&2Room_Elder`), 0, floor(`1&2Room_Elder` ) )) %>%
mutate("3Room_Elder" = if_else(is.na(`3Room_Elder`), 0, floor(`3Room_Elder` ) )) %>%
mutate("4Room_Elder" = if_else(is.na(`4Room_Elder`), 0, floor(`4Room_Elder` ) )) %>%
mutate("5Room_Elder" = if_else(is.na(`5Room_Elder`), 0, floor(`5Room_Elder` ) )) %>%
dplyr:::select(`SUBZONE_N`, `PLN_AREA_N.x`, `HDB`,`TOTAL.x`,`Percentage_HDB`,`1&2Room_Elder`,`3Room_Elder`,`4Room_Elder`,`5Room_Elder`,`PercentageElder`,`Elder_HDB`,`Elder`)

```

# Data Preparation - Left Join
```{r}
subzone_hdb_postal <- readOGR(dsn="data",layer="SUBZONE_HDB_POSTAL")
subzone_hdb_postal_elder  <- left_join(subzone_hdb_postal@data, subzone_age_gender_dwelling_type_elder, by = c("SUBZONE_N" = "SUBZONE_N"))
```

```{r}
subzone_hdb_postal_elder_clean <- subzone_hdb_postal_elder %>%
mutate(`X1room` = as.numeric(as.character(`X1room`))) %>%
mutate(`X2room` = as.numeric(as.character(`X2room`))) %>%
mutate(`X3room` = as.numeric(as.character(`X3room`))) %>%
mutate(`X4room` = as.numeric(as.character(`X4room`))) %>%
mutate(`X5room` = as.numeric(as.character(`X5room`))) %>%
mutate(`EF` = as.numeric(as.character(`EF`))) %>%
mutate(`X1X2Room` =  rowSums(.[2:3]) ) %>%
mutate(`X5ExRoom` = rowSums(.[6:7]) ) %>%
group_by(`SUBZONE_N`) %>%
mutate(TotalPopX1X2 = sum(`X1X2Room`)) %>%
mutate(TotalPopX3 = sum(`X3room`)) %>%
mutate(TotalPopX4 = sum(`X4room`)) %>%
mutate(TotalPopX5Ex = sum(`X5ExRoom`)) %>%
mutate(PercentageX1X2 = (`X1X2Room` / `TotalPopX1X2`) * 100) %>%
mutate(PercentageX3 = (`X3room` / `TotalPopX3`) * 100) %>%
mutate(PercentageX4 = (`X4room` / `TotalPopX4`) * 100) %>%
mutate(PercentageX5Ex = (`X5ExRoom` / `TotalPopX5Ex`) * 100) %>%
mutate("1&2Room_Elder_HDB" = (`PercentageX1X2` / 100) * `1&2Room_Elder`) %>%
mutate("3Room_Elder_HDB" = (`PercentageX3` / 100) * `3Room_Elder`) %>%
mutate("4Room_Elder_HDB" = (`PercentageX4` / 100) * `4Room_Elder`) %>%
mutate("5Room_Elder_HDB" = (`PercentageX5Ex` / 100) * `5Room_Elder`) %>%
mutate("1&2Room_Elder_HDB" = if_else(is.na(`1&2Room_Elder_HDB`), 0, round(`1&2Room_Elder_HDB` ) )) %>%
mutate("3Room_Elder_HDB" = if_else(is.na(`3Room_Elder_HDB`), 0, round(`3Room_Elder_HDB` ) )) %>%
mutate("4Room_Elder_HDB" = if_else(is.na(`4Room_Elder_HDB`), 0, round(`4Room_Elder_HDB` ) )) %>%
mutate("5Room_Elder_HDB" = if_else(is.na(`5Room_Elder_HDB`), 0, round(`5Room_Elder_HDB` ) )) %>%
  mutate("Total_Elder_HDB" = `1&2Room_Elder_HDB` + `3Room_Elder_HDB` + `4Room_Elder_HDB` + `5Room_Elder_HDB` )
#dplyr:::select(`POSTAL`,`SUBZONE_N`, `PLN_AREA_N`,`1&2Room_Elder_HDB`,`3Room_Elder_HDB`,`4Room_Elder_HDB`,`5Room_Elder_HDB`)
  #select(`POSTAL`,`SUBZONE_N`, `PLN_AREA_N`,`1&2Room_PreSch`,`X1X2Room`,`1&2Room_PreSch_HDB`,`3Room_PreSch`,`X3room`,`3Room_PreSch_HDB`,`4Room_PreSch`,`X4room`,`4Room_PreSch_HDB`,`5Room_PreSch`,`X5ExRoom`,`5Room_PreSch_HDB`)
# as.numeric(as.character(subzone_hdb_postal_presch_clean$lng[1]))
# as.numeric(as.character(subzone_hdb_postal_presch_clean$lat[1]))
scalenum <- scale(subzone_hdb_postal_elder_clean$Total_Elder_HDB)
scalenum
      #pal = colorNumeric(colorRamp(c('green', 'red')), subzone_hdb_postal_elder_clean$Total_Elder_HDB )
```

```{r}

#subzone_hdb_postal_elder_clean <- st_transform(subzone_hdb_postal_elder_clean, 4326)

icon_hdb <- awesomeIcons(
        icon = 'fa-home',
        iconColor = 'black',
        library = 'fa',
        markerColor = 'cadetblue'
      )

    leaflet() %>% addTiles() %>% 
   addAwesomeMarkers(data=subzone_hdb_postal_elder_clean, icon=icon_hdb,
                            popup = paste("Planning Area: ", subzone_hdb_postal_elder_clean$`PLN_AREA_N`, "<br>",
                                          "Subzone: ", subzone_hdb_postal_elder_clean$`SUBZONE_N`, "<br>",
                                          "Total Population in Subzone: ", subzone_hdb_postal_elder_clean$`TOTAL.x`, "<br>",
                                          "Total Population living in HDB in Subzone: ", subzone_hdb_postal_elder_clean$`HDB` , "<br>",
                                          "Total Population of aged 0-4 in Subzone: ", subzone_hdb_postal_elder_clean$`Elder`, "<br>",
                                          "Total Population of aged 0-4 living in HDB in Subzone: ", subzone_hdb_postal_elder_clean$`Elder_HDB` , "<br>",
                                          "Postal Code: ", subzone_hdb_postal_elder_clean$`POSTAL` , "<br>",
                                          "Pre-Sch living at ",subzone_hdb_postal_elder_clean$`POSTAL`," in 1 and 2 Rooms: ", subzone_hdb_postal_elder_clean$`1&2Room_Elder_HDB`, "<br>",
                                          "Pre-Sch living at ",subzone_hdb_postal_elder_clean$`POSTAL`," in 3 Rooms: ", subzone_hdb_postal_elder_clean$`3Room_Elder_HDB`, "<br>",
                                          "Pre-Sch living at ",subzone_hdb_postal_elder_clean$`POSTAL`," in 4 Rooms: ", subzone_hdb_postal_elder_clean$`4Room_Elder_HDB`, "<br>",
                                          "Pre-Sch living at ",subzone_hdb_postal_elder_clean$`POSTAL`," in 5 Rooms and Executive: ", subzone_hdb_postal_elder_clean$`5Room_Elder_HDB`),
                            group = "HDB") %>%
      setView(lng = 103.8509, lat = 1.3800, zoom = 16)
```

