---
title: "If a Tree Fell In A Forest"
output: html_notebook
---


#Run only this 
```{r}

packages = c('tmap','sf','plyr','tidyverse', 'rgdal', 'maptools', 'rjson', 'XML', 'RCurl') 
for (p in packages){
  if(!require(p, character.only = T)){ 
    install.packages(p)
  }
  library(p,character.only = T) 
}

```



#...and this. 
```{r}
oneMapAddrs <- read.csv("data/sgPostalCode.csv")%>%
               select('POSTAL','X','Y','lat','lng')

hdbData <- read.csv("data/HDBTypeSpread.csv")

oneMapPostalLoc <- distinct(oneMapAddrs)
colnames(hdbData)[1] <- "POSTAL"

hdbData <-  merge(hdbData, oneMapPostalLoc, by = "POSTAL", all.hdbData = TRUE)
            
write.csv(hdbData, file = "data/HDBTypeSpread.csv",row.names=FALSE)

```




















------------------------------------DO NOT RUN BELOW THIS LINE------------------------------------

```{r}

#json_data <- fromJSON(file="data/buildings.json")

#oneMapAddrs <- json_data %>% 
#               map(~data.frame(as.list(unlist(.x)), stringsAsFactors = FALSE)) %>% 
#               bind_rows()

#write.csv(oneMapAddrs, file = "data/OneMapData.csv",row.names=FALSE)

oneMapAddrs <- read.csv("data/OneMapData.csv")

oneMapPostalCode <- oneMapAddrs%>%
                    select('POSTAL')
                    
oneMapPostalCode <- distinct(oneMapPostalCode)

count <- 44494 #set this to which row you wanna start scraping at 
#hdbData <- setNames(data.frame(matrix(ncol = 3, nrow = 0)), c("postCode", "actUseTypTxt", "count"))
hdbData <- read.csv("data/HDBData.csv")

```




```{r}
#just re run this chunk every time it runs into some weird error, it'll start at the last row you stopped. 

for(postalCodeRow in oneMapPostalCode){
    for(i in count : length(postalCodeRow)){
        post <- postalCodeRow[i][1]
        count <- i
        while( nchar(post) < 6 ){
          post <- paste("0",post,sep="")
        }
        postalCode <- paste("https://services2.hdb.gov.sg/webapp/BC16AWPropInfoXML/BC16SRetrieveResiUnitCountXML?systemID=BC16&programName=FI10&postalCode=", post,sep="")  
        data <- NULL
        while( is.null(data)  ) {
          try(
            data <- xmlParse(getURL(postalCode))
          )
        }       
        xml_data <- xmlToDataFrame(data)
        x <- as.integer(ncol(xml_data))

        if(x > 1L){
          keep <- c("postCode","actUseTypTxt","count")
          dat <- xml_data[keep]
          clean <- na.omit(dat) 
          hdbData <- rbind.fill(clean,hdbData)
          write.csv(hdbData, file = "data/HDBData.csv",row.names=FALSE)
          cat(paste(post, "<< HDB Postal Code \r\n"))
        }
#        cat( paste(post, "<< postal code \r\n") )
#        cat( paste(nrow(hdbData), "<< result count\r\n"))
#        cat( paste(count, "<< row count \r\n"))

    }
}

```

```{r}

checker <-  checker%>%
            spread('actUseTypTxt','count') 

checker[is.na(checker)] <- 0

write.csv(checker, file = "data/HDBTypeSpread.csv",row.names=FALSE)


checker <- merge(checker, oneMapAddrs)


```

